### ISSUE TITLE
Set the original R-matrix

### ISSUE THREAD

**Issue by miguelesteras** [rdgreene/sa_tsp#11]

**Comment by miguelesteras** [comment]
@rdgreene I completed part of the section. Only now I realize some of the info I wrote might belong to the section 1.2.

Have a look and edit as you feel necessary.

Miguel :muscle:

**Comment by rdgreene** [comment]
I have done this, hope you don't mind but I changed the table format to make it a bit bigger (there's no page limit right?) and also re-wrote it to explain it in a bit more detail (dynamic updates, added goal state reward for end state, etc...)

I've kept the old version there, so we can revert if you'd rather, let me know.... 🤘
