### ISSUE TITLE
Package functions in one script

### ISSUE THREAD

**Issue by rdgreene** [rdgreene/sa_tsp#24]
@miguelesteras 

I was thinking of putting all the functions into one script, as they are all specific to our Q-Learning project. I think this will make them easier to reference (all in one place), and tidy up the main script a bit (less files to import functions from). Thoughts?

🚀

**Comment by miguelesteras** [comment]
You mean the learning functions?
We might want to keep separate learning functions from plotting functions.

Miguel :bowtie:

**Comment by rdgreene** [comment]
Yes, just the learning functions!

**Comment by rdgreene** [comment]
Done: tspFunctions.py
