### ISSUE TITLE
Define a state transition function

### ISSUE THREAD

**Issue by rdgreene** [rdgreene/sa_tsp#4]
@rdgreene

**Comment by rdgreene** [comment]
Working on this now 🏃

**Comment by rdgreene** [comment]
⚡️ I have done this @miguelesteras, kept it very simple, let me know what you think ⚡️

**Comment by miguelesteras** [comment]
I love your style @rdgreene 💯 :heavy_exclamation_mark:

Do we need blue on the table title? 
I use blue/red to identify values from R/Q matrix respectively during Q-learning demo.
Could we change the titles to other color?

Miguel 🗿

**Comment by rdgreene** [comment]
Ah, no not at all. I just spied you'd used some blue and copied it! Didn't realise there was a colour coding to it...we need a style guide! I'll change it to something less blue this afternoon 🍻
